from SPR4P.TestCase.Acpi import *
from SPR4P.TestCase.BasicIO import *
from SPR4P.TestCase.BiosSetup import *
from SPR4P.TestCase.Bmc import *
from SPR4P.TestCase.BootDevice import *
from SPR4P.TestCase.BootOS import *
from SPR4P.TestCase.Cpu import *
from SPR4P.TestCase.Custom import *
from SPR4P.TestCase.Dfx import *
from SPR4P.TestCase.Equipment import *
from SPR4P.TestCase.Legacy import *
from SPR4P.TestCase.Memory import *
from SPR4P.TestCase.Os import *
from SPR4P.TestCase.Pch import *
from SPR4P.TestCase.Pcie import *
from SPR4P.TestCase.PowerEfficiency import *
from SPR4P.TestCase.PublicCloud import *
from SPR4P.TestCase.RedfishTest import *
from SPR4P.TestCase.Release import *
from SPR4P.TestCase.SecurePrivacy import *
from SPR4P.TestCase.Security import *
from SPR4P.TestCase.SingleBuild import *
from SPR4P.TestCase.Smbios import *
from SPR4P.TestCase.UpdateBIOS import *
from SPR4P.TestCase.VariableLoop import *
